server:
   port: 8090
spring:
   application:
      name: inventory
   datasource:
      url: jdbc:mysql://localhost:3306/inventory_db
      username: root
      password: Bleachh2233+
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
   config:
      import: optional:configserver:http://localhost:8888
eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka/